# Generated by Django 4.2.11 on 2024-04-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('With Credits', 'With Credits'), ('Without Credits', 'Without Credits')], max_length=100, verbose_name='Result')),
                ('student_comment', models.TextField(blank=True, null=True, verbose_name='Student Comment')),
                ('academic_affairs_comment', models.TextField(blank=True, null=True, verbose_name='Academic Affairs Comment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='account.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='department.term')),
            ],
            options={
                'verbose_name': 'Term Deletion Request',
                'verbose_name_plural': 'Term Deletion Requests',
            },
        ),
        migrations.CreateModel(
            name='StudyingCertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='study_files/', verbose_name='document')),
                ('certificate_issue_place', models.CharField(max_length=255, verbose_name='certificate issue place')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.term', verbose_name='term')),
            ],
            options={
                'verbose_name': 'Studying Certificate',
                'verbose_name_plural': 'Studying Certificates',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField(blank=True, null=True, verbose_name='request text')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='answer text')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='is reviewed')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.termcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.termcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='EmergencyDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('student_comment', models.TextField(blank=True, null=True)),
                ('academic_affairs_comment', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='Amend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('registered', 'Registered'), ('dropped', 'Dropped'), ('waitlisted', 'Waitlisted')], max_length=12, verbose_name='amend type')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10, verbose_name='request status')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.termcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
            options={
                'verbose_name': 'amend',
                'verbose_name_plural': 'amends',
            },
        ),
    ]
